const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {chromium}=require('playwright');
const url=process.env.DEMO_URL||'http://127.0.0.1:8765/';
(async()=>{
 const browser=await chromium.launch({headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});
 const page=await browser.newPage({viewport:{width:1600,height:1050},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',e=>{if(e.type()==='error'&&!e.text().includes('favicon'))errors.push(e.text());});
 await page.goto(url);await page.waitForFunction(()=>window.halab?.state().loaded===0,null,{timeout:30000});
 assert.equal(await page.locator('.asset').count(),await page.evaluate(()=>window.halab.manifest.assets.length));
 for(const name of ['traffic_cone','round_stool','red_tool_bag','sink_cabinet'])assert.equal(await page.locator(`.asset[data-name="${name}"]`).count(),1);
 assert.equal(await page.locator('.app-title').innerText(),'MocapLab Twin');
 const joints=await page.evaluate(()=>window.halab.manifest.articulations);
 const fixed=await page.evaluate(()=>{const g=window.halab.manifest.geoms.find(g=>g.name==='sofa_base');return {id:g.id,pose:window.halab.geomPose(g.id)};});
 const referenceRgb=await page.locator('#rendered-rgb').getAttribute('src');
 for(const joint of joints){
  if(['white_cabinet','sink_cabinet'].includes(joint.asset))assert(Math.abs(Math.abs(joint.open-joint.closed)-Math.PI)<1e-8,'Cabinet door must open 180 degrees');
  await page.locator('#search').fill(joint.asset.replaceAll('_',' '));await page.locator(`.asset[data-name="${joint.asset}"]`).click();
  const input=page.locator(`input[data-joint="${joint.id}"]`);const closed=await page.evaluate(id=>window.halab.geomPose(id),joint.geoms[0]);
  await input.check();const opened=await page.evaluate(id=>window.halab.geomPose(id),joint.geoms[0]);assert.notDeepEqual(opened,closed,joint.id);
  await page.locator('#top').click();assert(await input.isChecked());
  await input.uncheck();assert.deepEqual(await page.evaluate(id=>window.halab.geomPose(id),joint.geoms[0]),closed);
 }
 assert.deepEqual(await page.evaluate(id=>window.halab.geomPose(id),fixed.id),fixed.pose);
 assert.equal(await page.locator('#rendered-rgb').getAttribute('src'),referenceRgb);
 await page.locator('#open-all').check();
 assert((await page.evaluate(()=>window.halab.manifest.articulations.every(j=>window.halab.articulationState()[j.id]))));
 await page.locator('#articulations input').first().uncheck();assert(await page.locator('#open-all').evaluate(el=>el.indeterminate));
 await page.locator('#open-all').check();assert((await page.evaluate(()=>Object.values(window.halab.articulationState()))).every(Boolean));
 await page.locator('#open-all').uncheck();assert((await page.evaluate(()=>Object.values(window.halab.articulationState()))).every(v=>!v));
 await page.locator('#open-all').check();await page.locator('#close-all').click();assert(!(await page.locator('#open-all').isChecked()));
 assert((await page.evaluate(()=>Object.values(window.halab.articulationState()))).every(v=>v===false));
 await page.locator('#orbit').click();await page.locator('#search').fill('');
 await page.locator('#frame').fill('84');await page.waitForFunction(()=>window.halab.state().loaded===84);
 assert.match(await page.locator('#recorded-rgb').getAttribute('src'),/276231463953/);
 await page.locator('#follow').click();assert.equal(await page.evaluate(()=>window.halab.state().mode),'follow');
 await page.locator('#points').check();assert((await page.evaluate(()=>window.halab.state().rawPointCount))>1000);
 await page.locator('#dense').check();await page.locator('#frustums').check();
 const originalPoints=await page.evaluate(()=>window.halab.state().rawPointCount);await page.locator('#confidence').uncheck();assert((await page.evaluate(()=>window.halab.state().rawPointCount))>=originalPoints);
 assert.equal(await page.locator('#mae, #rmse, #overlap, #pixel-readout, #pair-status').count(),0);
 await page.locator('#error').check();assert.equal(await page.locator('#sim-depth-title').innerText(),'Absolute depth error');
 await page.locator('#wipe').check();assert(await page.locator('#render-figure').isHidden());await page.locator('#wipe-slider').fill('25');assert.match(await page.locator('#wipe-rgb').getAttribute('style'),/25%/);
 const compact=await page.locator('#wipe-wrap').boundingBox();await page.locator('#expand-wipe').click();assert(await page.locator('#wipe-dialog').isVisible());
 const expanded=await page.locator('.large-wipe-image').boundingBox();assert(expanded.width>compact.width*2);assert(Math.abs(expanded.width/expanded.height-4/3)<.01);
 await page.locator('#large-wipe-slider').fill('70');assert.equal(await page.locator('#wipe-slider').inputValue(),'70');assert.match(await page.locator('#large-rendered').getAttribute('style'),/70%/);
 await page.locator('#large-frame').fill('171');await page.waitForFunction(()=>window.halab.state().loaded===171);assert.equal(await page.locator('#large-recorded').getAttribute('src'),await page.locator('#recorded-rgb').getAttribute('src'));
 await page.locator('#large-next').click();await page.waitForFunction(()=>window.halab.state().loaded===172);assert.match(await page.locator('#large-frame-label').innerText(),/173/);
 await page.locator('#close-wipe').focus();await page.keyboard.press('ArrowLeft');await page.waitForFunction(()=>window.halab.state().loaded===171);await page.keyboard.press('ArrowRight');await page.waitForFunction(()=>window.halab.state().loaded===172);
 await page.keyboard.press('Escape');assert(await page.locator('#wipe-dialog').isHidden());assert.equal(await page.locator('#frame').inputValue(),'172');assert(await page.locator('#expand-wipe').evaluate(el=>el===document.activeElement));
 await page.evaluate(()=>{window.halab.selectFrame(45);window.halab.selectFrame(120);window.halab.selectFrame(178);});await page.waitForFunction(()=>window.halab.state().loaded===178);
 assert.equal(await page.evaluate(()=>window.halab.state().index),178);await page.locator('#next').click();assert.equal(await page.evaluate(()=>window.halab.state().index),178);
 await page.locator('#frame').fill('0');await page.waitForFunction(()=>window.halab.state().loaded===0);await page.locator('#speed').selectOption('10');await page.locator('#play').click();await page.waitForFunction(()=>window.halab.state().index>0);await page.locator('#play').click();assert.equal(await page.evaluate(()=>window.halab.state().playing),false);
 await page.locator('#orbit').click();await page.locator('#points').uncheck();await page.locator('#dense').uncheck();await page.locator('#frustums').uncheck();await page.locator('#wipe').uncheck();await page.locator('#error').uncheck();await page.locator('#confidence').check();await page.locator('#frame').fill('0');await page.waitForFunction(()=>window.halab.state().loaded===0);
 await page.locator('#search').fill('divider');assert.equal(await page.locator('.asset').count(),0);await page.locator('#search').fill('sofa');assert.equal(await page.locator('.asset').count(),2);await page.locator('.asset').first().click();assert.match(await page.locator('#selection').innerText(),/Sofa/);await page.locator('#search').fill('');

 await page.waitForFunction(()=>!window.halab.viewState().focusing);
 const focused=await page.evaluate(()=>window.halab.viewState());
 assert(Math.hypot(...focused.target)>1,'Asset selection should move the orbit target');
 assert(Math.hypot(...focused.position.map((v,i)=>v-focused.target[i]))<10,'Selected sofa should fill more of the view');
 await page.locator('#follow').click();await page.locator('.asset[data-name="white_cabinet"]').click();await page.waitForFunction(()=>!window.halab.viewState().focusing);
 assert.equal(await page.evaluate(()=>window.halab.state().mode),'orbit');
 const cabinet=await page.evaluate(()=>window.halab.viewState());assert.notDeepEqual(cabinet.target,focused.target);
 await page.locator('.asset[data-name="bed"]').click();await page.locator('#top').click();assert.equal(await page.evaluate(()=>window.halab.viewState().focusing),false);
 assert.deepEqual(await page.evaluate(()=>window.halab.viewState().target),[0,0,0]);
 await page.emulateMedia({reducedMotion:'reduce'});await page.locator('.asset[data-name="white_cabinet"]').click();
 assert.equal(await page.evaluate(()=>window.halab.viewState().focusing),false);assert.deepEqual(await page.evaluate(()=>window.halab.viewState().target),cabinet.target);
 await page.emulateMedia({reducedMotion:'no-preference'});
 await page.reload();await page.waitForFunction(()=>window.halab?.state().loaded===0);
 await page.screenshot({path:path.join(__dirname,'../mujoco_scene/web_preview.png'),fullPage:true});
 await page.setViewportSize({width:390,height:844});assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));await page.locator('#frame').fill('75');await page.waitForFunction(()=>window.halab.state().loaded===75);await page.screenshot({path:path.join(__dirname,'../mujoco_scene/web_mobile_preview.png'),fullPage:true});
 await page.locator('#expand-wipe').click();const mobileWipe=await page.locator('.large-wipe-image').boundingBox();assert(mobileWipe.width<=390);assert(Math.abs(mobileWipe.width/mobileWipe.height-4/3)<.01);
 await page.locator('#large-frame').fill('0');await page.waitForFunction(()=>window.halab.state().loaded===0);assert(await page.locator('#large-prev').isDisabled());await page.locator('#close-wipe').click();
 assert.deepEqual(errors,[]);
 const report={url,desktop:true,mobile:true,consoleErrors:errors,checks:['frame synchronization','rapid selection race','first/last frame bounds','calibrated camera follow','raw depth points','confidence masking','RGB wipe','expanded wipe synchronization and navigation','modal keyboard and mobile layout','depth error view','trajectory playback','asset search/selection','asset camera focus and mode cancellation','reduced-motion focus','global door/drawer toggle and mixed state','mobile overflow','door and drawer toggles','joint reset','fixed geometry unchanged']};
 if(!process.env.DEMO_URL)fs.writeFileSync(path.join(__dirname,'../mujoco_scene/browser_validation.json'),JSON.stringify(report,null,2)+'\n');
 console.log(JSON.stringify(report,null,2));await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
