import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
const $=id=>document.getElementById(id);
const state={index:0,loaded:-1,mode:'orbit',playing:false,pair:null,selected:null};
let manifest,renderer,scene,camera,controls,framePoints,pathLine,denseLine,allFrustums,currentFrustum,rawPoints;
const meshList=[],assetMeshes=new Map(),cache=new Map(),meshById=new Map(),jointStates=new Map();
let token=0,playClock=0,playStart=0,lastTime=performance.now();
const wallClip=new THREE.Plane(new THREE.Vector3(0,0,-1),1.2);
const raycaster=new THREE.Raycaster();raycaster.params.Points.threshold=.10;
const corners=(f,d)=>{const k=f.intrinsics;return [[0,0],[k.width,0],[k.width,k.height],[0,k.height]].map(([u,v])=>new THREE.Vector3((u-k.cx)/k.fx*d,-(v-k.cy)/k.fy*d,-d).applyMatrix4(matrix(f.camera_to_world)));};
function matrix(t){return new THREE.Matrix4().set(...t.flat());}
function framePosition(f){return new THREE.Vector3(...f.camera_to_world.slice(0,3).map(r=>r[3]));}
function frustumVertices(f,d){const p=framePosition(f),cs=corners(f,d),a=[];cs.forEach((c,i)=>a.push(...p.toArray(),...c.toArray(),...c.toArray(),...cs[(i+1)%4].toArray()));return a;}
function human(n){return n.replaceAll('_',' ').replace(/\b\w/g,s=>s.toUpperCase());}
function timeLabel(t){return `${String(Math.floor(t/60)).padStart(2,'0')}:${(t%60).toFixed(3).padStart(6,'0')}`;}
function tellError(message){$('error-message').hidden=!message;$('error-message').textContent=message||'';}
function makeGeometry(g){const s=g.size;switch(g.type){case 'mesh':{const x=new THREE.BufferGeometry();x.setAttribute('position',new THREE.Float32BufferAttribute(g.mesh.vertices.flat(),3));x.setIndex(g.mesh.faces.flat());x.computeVertexNormals();const expanded=x.toNonIndexed();x.dispose();if(g.mesh.texcoords)expanded.setAttribute('uv',new THREE.Float32BufferAttribute(g.mesh.facetexcoords.flatMap(face=>face.flatMap(i=>g.mesh.texcoords[i])),2));return expanded;}case 'box':return new THREE.BoxGeometry(2*s[0],2*s[1],2*s[2]);case 'sphere':return new THREE.SphereGeometry(s[0],16,12);case 'cylinder':{const x=new THREE.CylinderGeometry(s[0],s[0],2*s[1],16);x.rotateX(Math.PI/2);return x;}case 'capsule':{const x=new THREE.CapsuleGeometry(s[0],2*s[1],6,12);x.rotateX(Math.PI/2);return x;}default:throw Error(`Unsupported geom ${g.type}`);}}
const textureLoader=new THREE.TextureLoader(),textureCache=new Map();
function sceneTexture(spec){const key=JSON.stringify(spec);if(!textureCache.has(key)){const t=textureLoader.load(spec.url);t.colorSpace=THREE.SRGBColorSpace;t.wrapS=t.wrapT=THREE.RepeatWrapping;t.repeat.set(...spec.repeat);t.anisotropy=renderer.capabilities.getMaxAnisotropy();textureCache.set(key,t);}return textureCache.get(key);}
function setupScene(){
 const stage=$('stage');scene=new THREE.Scene();scene.background=new THREE.Color('#f5f4f0');
 renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.localClippingEnabled=true;renderer.setClearColor('#f5f4f0');stage.append(renderer.domElement);
 camera=new THREE.PerspectiveCamera(48,1,.025,60);camera.up.set(0,0,1);camera.position.set(-6.8,-8.5,8);
 controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,0,0);controls.enableDamping=true;controls.minDistance=.15;controls.maxDistance=35;controls.maxPolarAngle=Math.PI*.95;
 scene.add(new THREE.HemisphereLight(0xffffff,0x96918a,2.5));const light=new THREE.DirectionalLight(0xffffff,2.0);light.position.set(-4,-6,12);scene.add(light);
 for(const g of manifest.geoms){
  const color=new THREE.Color(...g.rgba.slice(0,3));const material=new THREE.MeshStandardMaterial({color,roughness:1-(g.shininess||.1)*.7,metalness:g.specular>.4?.5:0,side:THREE.DoubleSide,flatShading:g.name==='concrete_pillar'||g.name.startsWith('floor'),transparent:g.rgba[3]<1,opacity:g.rgba[3]});
  const geometry=makeGeometry(g);
  if(g.texture){material.map=sceneTexture(g.texture);if(g.type==='box'&&g.texture.uniform){const positions=geometry.attributes.position,normals=geometry.attributes.normal,uv=[];for(let i=0;i<positions.count;i++){const n=[Math.abs(normals.getX(i)),Math.abs(normals.getY(i)),Math.abs(normals.getZ(i))],p=[positions.getX(i),positions.getY(i),positions.getZ(i)],axis=n.indexOf(Math.max(...n));uv.push(p[(axis+1)%3],p[(axis+2)%3]);}geometry.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));}}
  const mesh=new THREE.Mesh(geometry,material);mesh.position.fromArray(g.position);mesh.quaternion.setFromRotationMatrix(new THREE.Matrix4().set(...g.rotation[0],0,...g.rotation[1],0,...g.rotation[2],0,0,0,0,1));mesh.userData=g;mesh.userData.referencePosition=mesh.position.clone();mesh.userData.referenceQuaternion=mesh.quaternion.clone();meshById.set(g.id,mesh);scene.add(mesh);meshList.push(mesh);
  if(!assetMeshes.has(g.asset))assetMeshes.set(g.asset,[]);assetMeshes.get(g.asset).push(mesh);
 }
 const positions=manifest.frames.flatMap(f=>framePosition(f).toArray());
 pathLine=new THREE.Line(new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute(positions,3)),new THREE.LineBasicMaterial({color:'#163d5c',transparent:true,opacity:.8}));scene.add(pathLine);
 const markerColors=manifest.frames.flatMap((_,i)=>new THREE.Color().setHSL(.61-i/manifest.frames.length*.04,.45,.35).toArray());
 framePoints=new THREE.Points(new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute(positions,3)).setAttribute('color',new THREE.Float32BufferAttribute(markerColors,3)),new THREE.PointsMaterial({size:.065,vertexColors:true,sizeAttenuation:true,depthTest:false}));framePoints.renderOrder=3;scene.add(framePoints);
 denseLine=new THREE.Line(new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute(manifest.raw_arkit_trajectory.flatMap(p=>p.position),3)),new THREE.LineBasicMaterial({color:'#d19a00',transparent:true,opacity:.7}));denseLine.visible=false;scene.add(denseLine);
 allFrustums=new THREE.LineSegments(new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute(manifest.frames.flatMap(f=>frustumVertices(f,.13)),3)),new THREE.LineBasicMaterial({color:'#42617b',transparent:true,opacity:.35}));allFrustums.visible=false;scene.add(allFrustums);
 currentFrustum=new THREE.LineSegments(new THREE.BufferGeometry(),new THREE.LineBasicMaterial({color:'#cf9300',depthTest:false}));currentFrustum.renderOrder=4;scene.add(currentFrustum);
 let down=null;renderer.domElement.addEventListener('pointerdown',e=>down=[e.clientX,e.clientY]);renderer.domElement.addEventListener('pointerup',e=>{if(!down||Math.hypot(e.clientX-down[0],e.clientY-down[1])>5)return;const rect=renderer.domElement.getBoundingClientRect();raycaster.setFromCamera(new THREE.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const points=framePoints.visible?raycaster.intersectObject(framePoints):[];if(points.length){pause();selectFrame(points[0].index);return;}const hits=raycaster.intersectObjects(meshList.filter(m=>m.visible));if(hits.length)selectAsset(hits[0].object.userData.asset);});
 new ResizeObserver(resize).observe(stage);resize();updateLayers();
}
function resize(){if(!renderer)return;const w=$('stage').clientWidth,h=$('stage').clientHeight;renderer.setSize(w,h,false);camera.aspect=w/h;camera.fov=THREE.MathUtils.radToDeg(2*Math.atan(Math.tan(THREE.MathUtils.degToRad(24))*Math.max(1,1.35/camera.aspect)));camera.updateProjectionMatrix();if(state.mode==='follow')followCamera();}
function updateLayers(){const mode=$('wall-mode').value;wallClip.constant=+$('cut-height').value;$('cut-value').value=`${wallClip.constant.toFixed(2)} m`;$('cut-row').hidden=mode!=='cut';for(const mesh of meshList){const g=mesh.userData,isWall=[2,3].includes(g.group),isCeiling=g.group===4;mesh.visible=isCeiling?$('ceiling').checked:isWall?mode!=='hide':g.asset==='room'||$('furniture').checked;mesh.material.clippingPlanes=isWall&&mode==='cut'?[wallClip]:[];mesh.material.needsUpdate=true;}pathLine.visible=framePoints.visible=$('path').checked;denseLine.visible=$('dense').checked;allFrustums.visible=$('frustums').checked;if(rawPoints)rawPoints.visible=$('points').checked;}
function setMode(mode){state.mode=mode;for(const id of ['orbit','top','follow'])$(id).setAttribute('aria-pressed',String(id===mode));controls.enabled=mode!=='follow';$('view-label').textContent={orbit:'Orbit view',top:'Plan view',follow:'Recorded camera view'}[mode];if(mode==='follow'){$('wall-mode').value='full';$('ceiling').checked=true;updateLayers();followCamera();}else{camera.up.set(0,0,1);camera.fov=48;camera.aspect=$('stage').clientWidth/$('stage').clientHeight;camera.updateProjectionMatrix();camera.position.set(...(mode==='top'?[0,-.01,14]:[-6.8,-8.5,8]));controls.target.set(0,0,0);if($('wall-mode').value==='full'){$('wall-mode').value='cut';$('ceiling').checked=false;updateLayers();}controls.update();resize();}}
function followCamera(){const f=manifest.frames[state.index],T=matrix(f.camera_to_world),k=f.intrinsics,n=.025;camera.position.setFromMatrixPosition(T);camera.quaternion.setFromRotationMatrix(T);camera.projectionMatrix.makePerspective(-k.cx/k.fx*n,(k.width-k.cx)/k.fx*n,k.cy/k.fy*n,-(k.height-k.cy)/k.fy*n,n,60);camera.projectionMatrixInverse.copy(camera.projectionMatrix).invert();camera.updateMatrixWorld();}
function selectAsset(name){state.selected=name;for(const m of meshList)m.material.emissive.set(m.userData.asset===name?'#58420b':'#000000');document.querySelectorAll('.asset').forEach(b=>b.classList.toggle('selected',b.dataset.name===name));const item=manifest.assets.find(x=>x.name===name);$('selection').textContent=item?`${human(name)} · ${item.dimensions_m?.map(v=>v.toFixed(2)).join(' × ')||'estimated'} m${item.panels?' · 4 panels / 3 hinges':''}`:human(name);renderArticulations();}
function assetList(){const query=$('search').value.toLowerCase();$('assets').replaceChildren();manifest.assets.filter(a=>a.name.replaceAll('_',' ').includes(query)).forEach(a=>{const b=document.createElement('button');b.className='asset';b.dataset.name=a.name;b.append(document.createTextNode(human(a.name)));const tag=document.createElement('span');const joints=(manifest.articulations||[]).filter(j=>j.asset===a.name);tag.textContent=joints.length?joints.some(j=>j.type==='slide')?'DRAWERS':'DOORS':a.panels?'4 PANELS':a.movable?'FREE':'FIXED';b.append(tag);b.onclick=()=>selectAsset(a.name);$('assets').append(b);});}
function setArticulation(id,open){
 const joint=manifest.articulations.find(j=>j.id===id);if(!joint)return;
 const delta=(open?joint.open:joint.closed)-joint.closed,axis=new THREE.Vector3(...joint.axis),anchor=new THREE.Vector3(...joint.anchor),rotation=new THREE.Quaternion().setFromAxisAngle(axis,delta);
 for(const geomId of joint.geoms){const mesh=meshById.get(geomId);if(!mesh)continue;mesh.position.copy(mesh.userData.referencePosition);mesh.quaternion.copy(mesh.userData.referenceQuaternion);if(joint.type==='hinge'){mesh.position.sub(anchor).applyQuaternion(rotation).add(anchor);mesh.quaternion.premultiply(rotation);}else mesh.position.addScaledVector(axis,delta);mesh.updateMatrixWorld();}
 jointStates.set(id,open);$('close-all').hidden=![...jointStates.values()].some(Boolean);for(const input of $('articulations').querySelectorAll('input'))input.checked=jointStates.get(input.dataset.joint)||false;
}
function renderArticulations(){
 $('articulations').replaceChildren();
 for(const joint of manifest.articulations||[]){if(joint.asset!==state.selected)continue;const label=document.createElement('label'),input=document.createElement('input');input.type='checkbox';input.checked=jointStates.get(joint.id)||false;input.dataset.joint=joint.id;input.setAttribute('aria-label',`${human(joint.asset)} ${joint.label}`);input.onchange=()=>setArticulation(joint.id,input.checked);label.append(document.createTextNode(joint.label),input);$('articulations').append(label);}
}
async function fetchBytes(url,length){const r=await fetch(url);if(!r.ok)throw Error(`${url}: HTTP ${r.status}`);const b=await r.arrayBuffer();if(b.byteLength!==length)throw Error(`Unexpected data size: ${url}`);return b;}
function loadImage(url){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(Error(`Cannot load ${url}`));image.src=url;});}
function loadPair(i){if(cache.has(i))return cache.get(i);const f=manifest.frames[i];const result=Promise.all([loadImage(f.rgb),loadImage(f.render_rgb),fetchBytes(f.depth,256*192*2),fetchBytes(f.render_depth,256*192*2),fetchBytes(f.confidence,256*192)]).then(([rgb,sim,depth,renderDepth,confidence])=>({rgb,sim,depth:new Uint16Array(depth),renderDepth:new Uint16Array(renderDepth),confidence:new Uint8Array(confidence)}));cache.set(i,result);result.catch(()=>cache.delete(i));if(cache.size>16)cache.delete(cache.keys().next().value);return result;}
async function selectFrame(index){
 index=Math.max(0,Math.min(manifest.frames.length-1,Math.round(index)));state.index=index;const f=manifest.frames[index],request=++token;$('frame').value=index;$('frame-label').textContent=`FRAME ${String(index+1).padStart(3,'0')} / ${manifest.frames.length}`;$('timestamp').textContent=timeLabel(f.time_s);$('camera-label').textContent=`CAM ${String(index+1).padStart(3,'0')}`;
 currentFrustum.geometry.dispose();currentFrustum.geometry=new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute(frustumVertices(f,.48),3));if(state.mode==='follow')followCamera();$('pair-status').textContent=`Loading pair ${index+1}…`;
 try{const pair=await loadPair(index);if(request!==token)return;state.pair=pair;state.loaded=index;$('recorded-rgb').src=pair.rgb.src;$('rendered-rgb').src=$('wipe-rgb').src=pair.sim.src;drawDepth();buildPoints();$('pair-status').textContent='Reference state · calibrated intrinsics · full room';tellError('');if(index+1<manifest.frames.length)loadPair(index+1).catch(()=>{});}catch(e){if(request===token){tellError(e.message);$('pair-status').textContent='Pair unavailable';}}
}
const palette=[[19,49,82],[98,126,163],[219,217,78],[242,118,56],[189,52,77]];
function color(t){t=Math.max(0,Math.min(.999999,t))*4;const i=Math.floor(t),f=t-i;return palette[i].map((c,k)=>Math.round(c*(1-f)+palette[i+1][k]*f));}
function validPixel(i){const p=state.pair;return p.depth[i]>200&&p.depth[i]<9000&&(!$('confidence').checked||p.confidence[i]>=200);}
function drawDepth(){if(!state.pair)return;const p=state.pair,max=+$('depth-max').value,errorMode=$('error').checked;let n=0,abs=0,sq=0;const a=new ImageData(256,192),b=new ImageData(256,192);for(let i=0;i<256*192;i++){const valid=validPixel(i),simValid=p.renderDepth[i]>25&&p.renderDepth[i]<39900;const err=Math.abs(p.depth[i]-p.renderDepth[i])/1000;if(valid&&simValid){n++;abs+=err;sq+=err*err;}const ac=valid?color(p.depth[i]/1000/max):[28,32,38],bc=errorMode?(valid&&simValid?color(err):[28,32,38]):(simValid?color(p.renderDepth[i]/1000/max):[28,32,38]);a.data.set([...ac,255],i*4);b.data.set([...bc,255],i*4);} $('recorded-depth').getContext('2d').putImageData(a,0,0);$('rendered-depth').getContext('2d').putImageData(b,0,0);$('mae').textContent=n?`${(abs/n).toFixed(3)} m`:'N/A';$('rmse').textContent=n?`${Math.sqrt(sq/n).toFixed(3)} m`:'N/A';$('overlap').textContent=`${(100*n/(256*192)).toFixed(1)}%`;$('scale-max').textContent=errorMode?'≥1 m':`${max} m`;$('scale-label').textContent=errorMode?'ABSOLUTE ERROR · CLIPPED AT 1 M':'OPTICAL-AXIS DEPTH · METERS';$('sim-depth-title').textContent=errorMode?'Absolute depth error':'MuJoCo depth';$('error-unit').textContent=errorMode?'|render − recorded|':'256 × 192';}
function buildPoints(){if(rawPoints){scene.remove(rawPoints);rawPoints.geometry.dispose();rawPoints.material.dispose();rawPoints=null;}if(!$('points').checked||!state.pair||state.loaded!==state.index)return;const f=manifest.frames[state.loaded],p=state.pair,k=f.intrinsics,T=matrix(f.camera_to_world),positions=[],colors=[];const c=document.createElement('canvas');c.width=256;c.height=192;const ctx=c.getContext('2d');ctx.drawImage(p.rgb,0,0,256,192);const rgb=ctx.getImageData(0,0,256,192).data;for(let v=0;v<192;v+=2)for(let u=0;u<256;u+=2){const i=v*256+u;if(!validPixel(i))continue;const z=p.depth[i]/1000,pos=new THREE.Vector3(((u+.5)*4-k.cx)/k.fx*z,-((v+.5)*4-k.cy)/k.fy*z,-z).applyMatrix4(T);positions.push(...pos.toArray());const col=new THREE.Color().setRGB(rgb[i*4]/255,rgb[i*4+1]/255,rgb[i*4+2]/255,THREE.SRGBColorSpace);colors.push(...col.toArray());}rawPoints=new THREE.Points(new THREE.BufferGeometry().setAttribute('position',new THREE.Float32BufferAttribute(positions,3)).setAttribute('color',new THREE.Float32BufferAttribute(colors,3)),new THREE.PointsMaterial({size:.024,vertexColors:true}));scene.add(rawPoints);}
function pause(){state.playing=false;$('play').textContent='▶';$('play').setAttribute('aria-label','Play captured trajectory');}
function togglePlay(){if(state.playing){pause();return;}if(state.index===manifest.frames.length-1)selectFrame(0);state.playing=true;playClock=manifest.frames[state.index].time_s;playStart=performance.now();$('play').textContent='Ⅱ';$('play').setAttribute('aria-label','Pause captured trajectory');}
function wire(){$('close-all').onclick=()=>{for(const [id,open] of jointStates)if(open)setArticulation(id,false);};for(const mode of ['orbit','top','follow'])$(mode).onclick=()=>setMode(mode);for(const id of ['wall-mode','cut-height','ceiling','furniture','path','dense','frustums'])$(id).addEventListener('input',updateLayers);$('points').onchange=buildPoints;$('search').oninput=assetList;$('frame').oninput=()=>{pause();selectFrame(+$('frame').value);};$('prev').onclick=()=>{pause();selectFrame(state.index-1);};$('next').onclick=()=>{pause();selectFrame(state.index+1);};$('play').onclick=togglePlay;$('speed').onchange=()=>{if(state.playing){playClock=manifest.frames[state.index].time_s;playStart=performance.now();}};for(const id of ['error','depth-max','confidence'])$(id).onchange=()=>{drawDepth();if(id==='confidence')buildPoints();};$('wipe').onchange=()=>{const on=$('wipe').checked;$('images').classList.toggle('wipe-mode',on);$('render-figure').hidden=on;for(const id of ['wipe-rgb','wipe-line','wipe-slider'])$(id).hidden=!on;};$('wipe-slider').oninput=()=>{const v=$('wipe-slider').value;$('wipe-rgb').style.clipPath=`inset(0 0 0 ${v}%)`;$('wipe-line').style.left=`${v}%`;};for(const id of ['recorded-depth','rendered-depth'])$(id).onpointermove=e=>{if(!state.pair)return;const rect=e.target.getBoundingClientRect(),u=Math.min(255,Math.floor((e.clientX-rect.left)/rect.width*256)),v=Math.min(191,Math.floor((e.clientY-rect.top)/rect.height*192)),i=v*256+u,p=state.pair;const fmt=z=>z?(z/1000).toFixed(3)+' m':'invalid';$('pixel-readout').textContent=`(${u}, ${v}) · recorded ${fmt(p.depth[i])} · render ${fmt(p.renderDepth[i])} · confidence ${p.confidence[i]}/255`;};window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA','BUTTON'].includes(document.activeElement.tagName))return;if(e.code==='Space'){e.preventDefault();togglePlay();}if(e.key==='ArrowRight'){pause();selectFrame(state.index+1);}if(e.key==='ArrowLeft'){pause();selectFrame(state.index-1);}});}
function animate(now){requestAnimationFrame(animate);if(state.playing){const t=playClock+(now-playStart)/1000*+$('speed').value;let i=state.index;while(i+1<manifest.frames.length&&manifest.frames[i+1].time_s<=t)i++;if(i!==state.index)selectFrame(i);if(t>=manifest.duration_s)pause();}if(!renderer)return;if(state.mode!=='follow')controls.update();const w=$('stage').clientWidth,h=$('stage').clientHeight;renderer.setScissorTest(false);renderer.setViewport(0,0,w,h);renderer.clear();if(state.mode==='follow'){const rw=Math.min(w,h*4/3),rh=rw*3/4;renderer.setViewport((w-rw)/2,(h-rh)/2,rw,rh);renderer.setScissor((w-rw)/2,(h-rh)/2,rw,rh);renderer.setScissorTest(true);}renderer.render(scene,camera);lastTime=now;}
async function start(){try{const response=await fetch('data/manifest.json');if(!response.ok)throw Error('Dataset missing. Run scripts/export_web.py first.');manifest=await response.json();$('frame').max=manifest.frames.length-1;$('frame-count').textContent=manifest.frames.length;$('capture-duration').textContent=`${Math.floor(manifest.duration_s/60)}m ${Math.round(manifest.duration_s%60)}s`;$('asset-count').textContent=`${manifest.assets.length} OBJECTS`;$('room-size').textContent='fitted room shell';setupScene();wire();assetList();$('loading').remove();await selectFrame(0);requestAnimationFrame(animate);window.halab={selectFrame,setArticulation,articulationState:()=>Object.fromEntries(jointStates),geomPose:id=>{const mesh=meshById.get(id);return mesh?{position:mesh.position.toArray(),quaternion:mesh.quaternion.toArray()}:null;},state:()=>({index:state.index,loaded:state.loaded,mode:state.mode,playing:state.playing,rawPointCount:rawPoints?.geometry.attributes.position.count||0}),manifest};}catch(e){console.error(e);if($('loading'))$('loading').textContent=`Could not open viewer: ${e.message}`;tellError(e.message);}}
start();
